/** 文王序六十四卦上下卦（上卦 · 下卦）。 */
export const HEXAGRAM_TRIGRAMS: Record<number, { upper: string; lower: string }> = {
  1: { upper: '天', lower: '天' },
  2: { upper: '地', lower: '地' },
  3: { upper: '水', lower: '雷' },
  4: { upper: '山', lower: '水' },
  5: { upper: '水', lower: '天' },
  6: { upper: '天', lower: '水' },
  7: { upper: '地', lower: '水' },
  8: { upper: '水', lower: '地' },
  9: { upper: '風', lower: '天' },
  10: { upper: '天', lower: '澤' },
  11: { upper: '地', lower: '天' },
  12: { upper: '天', lower: '地' },
  13: { upper: '天', lower: '火' },
  14: { upper: '火', lower: '天' },
  15: { upper: '地', lower: '山' },
  16: { upper: '雷', lower: '地' },
  17: { upper: '澤', lower: '雷' },
  18: { upper: '山', lower: '風' },
  19: { upper: '地', lower: '澤' },
  20: { upper: '風', lower: '地' },
  21: { upper: '火', lower: '雷' },
  22: { upper: '山', lower: '火' },
  23: { upper: '山', lower: '地' },
  24: { upper: '地', lower: '雷' },
  25: { upper: '天', lower: '雷' },
  26: { upper: '山', lower: '天' },
  27: { upper: '山', lower: '雷' },
  28: { upper: '澤', lower: '風' },
  29: { upper: '水', lower: '水' },
  30: { upper: '火', lower: '火' },
  31: { upper: '澤', lower: '山' },
  32: { upper: '雷', lower: '風' },
  33: { upper: '天', lower: '山' },
  34: { upper: '雷', lower: '天' },
  35: { upper: '火', lower: '地' },
  36: { upper: '地', lower: '火' },
  37: { upper: '風', lower: '火' },
  38: { upper: '火', lower: '澤' },
  39: { upper: '水', lower: '山' },
  40: { upper: '雷', lower: '水' },
  41: { upper: '山', lower: '澤' },
  42: { upper: '風', lower: '雷' },
  43: { upper: '澤', lower: '天' },
  44: { upper: '天', lower: '風' },
  45: { upper: '澤', lower: '地' },
  46: { upper: '地', lower: '風' },
  47: { upper: '澤', lower: '水' },
  48: { upper: '水', lower: '風' },
  49: { upper: '澤', lower: '火' },
  50: { upper: '火', lower: '風' },
  51: { upper: '雷', lower: '雷' },
  52: { upper: '山', lower: '山' },
  53: { upper: '風', lower: '山' },
  54: { upper: '雷', lower: '澤' },
  55: { upper: '雷', lower: '火' },
  56: { upper: '火', lower: '山' },
  57: { upper: '風', lower: '風' },
  58: { upper: '澤', lower: '澤' },
  59: { upper: '風', lower: '水' },
  60: { upper: '水', lower: '澤' },
  61: { upper: '風', lower: '澤' },
  62: { upper: '雷', lower: '山' },
  63: { upper: '水', lower: '火' },
  64: { upper: '火', lower: '水' },
};

export function trigramsOf(index: number): { upper: string; lower: string } {
  return HEXAGRAM_TRIGRAMS[index] ?? { upper: '', lower: '' };
}
